{
  lib,
  pkgs,
  username,
  useremail,
  my,
  ...
}: {
  # `programs.git` will generate the config file: ~/.config/git/config
  # to make git use this config file, `~/.gitconfig` should not exist!
  #
  #    https://git-scm.com/docs/git-config#Documentation/git-config.txt---global
  home.activation.removeExistingGitconfig = lib.hm.dag.entryBefore ["checkLinkTargets"] ''
    rm -f ~/.gitconfig
  '';

  # Syntax-highlighting pager for git (moved out of programs.git.delta,
  # which home-manager renamed to this top-level option)
  programs.delta = {
    enable = true;
    enableGitIntegration = true;
  };

  programs.git = {
    enable = true;
    lfs.enable = true;

    ignores = ["*~" "*.swp" "\\#*\\#" ".\\#*" ".vim/coc-settings.json" ".vscode" ".envrc"]; # vim swap file & emacs

    # Work identity overrides for any repo under ~/work/.
    # The included file is generated by home-manager from `contents`
    # below — no manual ~/work/.gitconfig needed.
    includes = [
      {
        condition = "gitdir:~/work/";
        contents = {
          user = {
            name = my.gpg.work.name;
            email = my.gpg.work.email;
            signingKey = my.gpg.work.fingerprint;
          };
        };
      }
    ];

    settings = {
      # User & signing — personal identity (default outside ~/work/).
      # Email must match a UID on the GPG key AND a verified email on
      # the GitHub account, otherwise GitHub marks commits Unverified
      # even though the signature is real.
      user.name = my.gpg.personal.name;
      user.email = my.gpg.personal.email;
      user.signingKey = my.gpg.personal.fingerprint;
      commit.gpgSign = true;
      tag.gpgSign = true;

      # Pull.
      pull.ff = "only";

      # Diff & merge.
      diff.external = "${pkgs.difftastic}/bin/difft";
      diff.tool = "nvimdiff";
      difftool.prompt = false;
      merge.tool = "nvimdiff";
      merge.conflictstyle = "diff3";
      mergetool.prompt = false;
      rerere.enabled = true;

      # Pager.
      core.pager = "less";
      pager.branch = "less --quit-if-one-screen";
      pager.stash = "less --quit-if-one-screen";

      # Display.
      # Always show branches and tags for `git log` in `vim-fugitive`.
      # See: https://github.com/tpope/vim-fugitive/issues/1965
      log.decorate = true;
      # Show detailed diff by default for `git stash show`.
      stash.showPatch = true;

      # Misc.
      init.defaultBranch = "main";
      push.autoSetupRemote = true;
      advice.detachedHead = false;

      aliases = {
        # common aliases
        br = "branch";
        cmt = "commit -m";
        ca = "commit --amend -m";
        co = "checkout";
        cp = "cherry-pick";
        d = "diff";
        dc = "diff --cached";
        dt = "difftool";
        ls = "log --pretty=format:\"%C(yellow)%h%Cred%d\\\\ %Creset%s%Cblue\\\\ [%cn]\" --decorate";
        ll = "log --pretty=format:\"%C(yellow)%h%Cred%d\\\\ %Creset%s%Cblue\\\\ [%cn]\" --decorate --numstat";
        mt = "mergetool";
        st = "status";
        sub = "submodule";

        # aliases for submodule
        update = "submodule update --init --recursive";
        foreach = "submodule foreach";
      };
    };

    # signing = {
    #   key = "xxx";
    #   signByDefault = true;
    # };

    # delta = {
    #   enable = true;
    #   options = {
    #     features = "side-by-side";
    #   };
    # };
  };
}
